import { useState } from 'react';
import InteractivePlayground from '../InteractivePlayground';

export default function HashTablePlayground() {
  const [slots, setSlots] = useState<Array<number | 'T' | null>>([null, null, null, null, null, null, null]);
  const [next, setNext] = useState(10);
  const insert = () => { const value = next; const start = value % slots.length; const copy = [...slots]; for (let offset = 0; offset < slots.length; offset += 1) { const index = (start + offset) % slots.length; if (copy[index] === null || copy[index] === 'T') { copy[index] = value; setSlots(copy); setNext(next + 7); return; } } };
  const remove = (index: number) => { const copy = [...slots]; if (copy[index] !== null && copy[index] !== 'T') copy[index] = 'T'; setSlots(copy); };
  return <InteractivePlayground title="Probe collisions and tombstones" description="Insert keys that collide under h(k)=k mod 7, then remove one without breaking later searches." staticCaption="Open addressing must distinguish an unused slot from a deleted slot." staticContent={<div className="grid grid-cols-7 gap-1">{slots.map((value, index) => <div key={index} className="rounded border p-2 text-center text-sm">{value ?? '∅'}</div>)}</div>} status={`load = ${slots.filter((value) => value !== null && value !== 'T').length}/${slots.length}`}><div className="grid grid-cols-7 gap-1">{slots.map((value, index) => <button type="button" key={index} aria-label={`slot ${index}, ${value ?? 'empty'}`} onClick={() => remove(index)} className={`min-h-14 rounded border p-2 text-center text-sm ${value === 'T' ? 'border-amber-500 bg-amber-100' : value === null ? 'border-slate-300 dark:border-slate-600' : 'border-primary bg-primary/10 font-bold'}`}><span className="block text-xs text-slate-500">{index}</span>{value ?? '∅'}</button>)}</div><div className="mt-4 flex gap-3"><button type="button" className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-white" onClick={insert}>Insert colliding key</button><button type="button" className="rounded-lg border border-light-border px-4 py-2 text-sm font-bold dark:border-dark-border" onClick={() => setSlots(Array(7).fill(null))}>Reset</button></div><p className="mt-3 text-sm">Click a stored key to create a tombstone. Searches must continue past `T`.</p></InteractivePlayground>;
}
