name: Deploy LibreUni to Coolify

on:
  push:
    branches:
      - main # Change this to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X GET "${{ secrets.COOLIFY_WEBHOOK }}?force=true" \
          --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
